// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Wp2OWQRgHqA6UvjgiiXT61nOssStp10',
    appId: '1:1041041643130:web:584787d3dc0f5a2aa98dc3',
    messagingSenderId: '1041041643130',
    projectId: 'cqaag-gh',
    authDomain: 'cqaag-gh-68b3d.firebaseapp.com',
    storageBucket: 'cqaag-gh.appspot.com',
    measurementId: 'G-0MHYM4F7GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD71sRgAMvtRHGIxP4PxXvDA_ZMT5I3MU',
    appId: '1:1041041643130:android:bc120b8f5b2da927a98dc3',
    messagingSenderId: '1041041643130',
    projectId: 'cqaag-gh',
    storageBucket: 'cqaag-gh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEfLsa1vmA2HY-6YqyPMEATty9dLlSB6U',
    appId: '1:1041041643130:ios:963704bd3fc7bba0a98dc3',
    messagingSenderId: '1041041643130',
    projectId: 'cqaag-gh',
    storageBucket: 'cqaag-gh.appspot.com',
    iosClientId: '1041041643130-5r6u4gov45ip6009s2vt9dm6sk35ajoo.apps.googleusercontent.com',
    iosBundleId: 'com.cqaaqgh.cqaaqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEfLsa1vmA2HY-6YqyPMEATty9dLlSB6U',
    appId: '1:1041041643130:ios:8a962a3a7aa15b33a98dc3',
    messagingSenderId: '1041041643130',
    projectId: 'cqaag-gh',
    storageBucket: 'cqaag-gh.appspot.com',
    iosClientId: '1041041643130-kif4m3avp6dsfsgnnfa4o3t3bdrna68l.apps.googleusercontent.com',
    iosBundleId: 'com.cqaaqgh.cqaaqApp.RunnerTests',
  );
}
